# 机器人的 QQ 号和密码
botQQ: 1111
botPassword: this_is_password

# 允许机器人接受处理消息的群组
allowedGroups: [
    11111
]

# 机器人管理员 QQ
admins: [
    11111
]

# 启用的命令列表
enabledCommands: [
    about,
]

# 启用的 pipeline 列表
enabledPipelines: [
  repeat,
  log_message
]

# 启用的 timer 列表
enabledTimers: [
  life
]

# db filename
dbFilename: izumi.sqlite

# ColorImage 服务需要的配置
colorImageKey: 11223344

# SOCKS5 代理配置
useProxy: true
proxyIp: 127.0.0.1
proxyPort: 9050